# Generated by Django 6.0 on 2025-12-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature0', models.FloatField()),
                ('feature1', models.FloatField()),
                ('category', models.IntegerField()),
            ],
        ),
    ]
